// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissingPersonApi.Data;

namespace MissingPersonApi.Migrations
{
    [DbContext(typeof(MissingPersonApiContext))]
    partial class MissingPersonApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MissingPersonApi.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Msg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MissingPersonApi.Models.MissingReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cdetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ctitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Mdate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("MissingReport");
                });

            modelBuilder.Entity("MissingPersonApi.Models.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("MissingPersonApi.Models.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cdetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ctitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Mdate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Report");
                });
#pragma warning restore 612, 618
        }
    }
}
